// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerState
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Typing")]
        public string? Typing;

        public PlayerState(
            SpacetimeDB.Identity Identity,
            string? Typing
        )
        {
            this.Identity = Identity;
            this.Typing = Typing;
        }

        public PlayerState()
        {
        }
    }
}
