// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerStateHandle : RemoteTableHandle<EventContext, PlayerState>
        {
            protected override string RemoteTableName => "PlayerState";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerState row) => row.Identity;

                public IdentityUniqueIndex(PlayerStateHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal PlayerStateHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(PlayerState row) => row.Identity;
        }

        public readonly PlayerStateHandle PlayerState;
    }
}
