// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetTypingHandler(ReducerEventContext ctx, string text);
        public event SetTypingHandler? OnSetTyping;

        public void SetTyping(string text)
        {
            conn.InternalCallReducer(new Reducer.SetTyping(text), this.SetCallReducerFlags.SetTypingFlags);
        }

        public bool InvokeSetTyping(ReducerEventContext ctx, Reducer.SetTyping args)
        {
            if (OnSetTyping == null) return false;
            OnSetTyping(
                ctx,
                args.Text
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetTyping : Reducer, IReducerArgs
        {
            [DataMember(Name = "text")]
            public string Text;

            public SetTyping(string Text)
            {
                this.Text = Text;
            }

            public SetTyping()
            {
                this.Text = "";
            }

            string IReducerArgs.ReducerName => "SetTyping";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetTypingFlags;
        public void SetTyping(CallReducerFlags flags) => SetTypingFlags = flags;
    }
}
